language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
    include:
        - php: hhvm
          dist: trusty
        - php: hhvm
          dist: trusty
          env: COMPOSER_OPTS="--prefer-lowest"
    fast_finish: true

sudo: false

env:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest"
    
before_install:
    - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then composer require --dev --no-update phpunit/phpunit ~5 ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.1" ]]; then composer require --dev --no-update phpunit/phpunit ~5 ; fi

before_script:
    - if [[ "$TRAVIS_PHP_VERSION" = "5.4" ]]; then pecl install mailparse-2.1.6 ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "5.5" ]]; then pecl install mailparse-2.1.6 ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then pecl install mailparse-2.1.6 ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then pecl install mailparse ; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "7.1" ]]; then pecl install mailparse ; fi
    - composer self-update
    - composer update $COMPOSER_OPTS

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
    - ./vendor/bin/phpcs src --standard=psr2
    - ./vendor/bin/phpcs tests --standard=psr2

after_script:
    - ./vendor/bin/coveralls -v
